FROM python:3.12-alpine

WORKDIR /app

#Install common utilities
RUN apk add --no-cache bash curl

COPY phase1/ ./phase1/
COPY phase2/ ./phase2/
COPY phase3/ ./phase3/

CMD ["echo", "Multimedia Pipeline System - Use docker-compose to run specific phases"]